name: douban
on: 
  schedule:
    - cron: "30 * * * *"
  workflow_dispatch: 

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
      # 1. 必须有这一步来获取仓库代码
      - name: Checkout
        uses: actions/checkout@v3

      # 2. 同步电影 (换成 maxojj 的版本)
      - name: movie
        uses: maxojj/doumark-action@master
        with:
          id: 1763879
          type: movie
          format: neodb
          neodb_token: ${{ secrets.NEODB_TOKEN }}
        
      # 3. 同步音乐
      - name: music
        uses: maxojj/doumark-action@master
        with:
          id: 1763879
          type: music
          format: neodb
          neodb_token: ${{ secrets.NEODB_TOKEN }}

      # 4. 保存结果（非常重要，否则数据不会存入你的 GitHub）
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "chore: update data from douban" || exit 0
          git push
